application: dspillini
version: 1
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
